-- ods_yxst_trd_order_di_o logical structure snapshot (FOREIGN TABLE in holodb)
-- Source: holodb.public.ods_yxst_trd_order_di_o (MaxCompute external table)
CREATE TABLE IF NOT EXISTS public.ods_yxst_trd_order_di_o (
    id bigint,
    source bigint,
    form_type text,
    root_order_id text,
    custom_order_no text,
    order_level text,
    order_finish_time text,
    order_type text,
    cust_memer_code text,
    goods_name text,
    goods_id text,
    goods_num text,
    goods_price numeric,
    tax_sale_amount numeric,
    tax_cost_amount numeric,
    supplier_member_code text,
    cost_order_id text,
    account_supplier_code text,
    account_cust_code text,
    business_code text,
    member_code text,
    fp_member_code text,
    sup_member_code text,
    product_id text,
    product_name text,
    sup_product_id text,
    product_category_l1 text,
    product_category_l2 text,
    product_category_l3 text,
    amt_out_sale numeric,
    create_date timestamptz,
    inventory_id text,
    stock_type text,
    goods_face numeric,
    fp_order_id text,
    fp_merchant_code text,
    customer_order_no text,
    pt text
);
