---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	proc_subgraph(proc_subgraph)
	manual_scheme_run_graph(manual_scheme_run_graph)
	manual_notify_followup_graph(manual_notify_followup_graph)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	router -.-> __end__;
	router -.-> proc_subgraph;
	router -.-> manual_scheme_run_graph;
	router -.-> manual_notify_followup_graph;
	proc_subgraph --> __end__;
	manual_scheme_run_graph --> __end__;
	manual_notify_followup_graph --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
