---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_scheme_node(load_scheme_node)
	resolve_manual_inputs_node(resolve_manual_inputs_node)
	check_manual_files_node(check_manual_files_node)
	build_manual_run_context_node(build_manual_run_context_node)
	scheme_execution_graph(scheme_execution_graph)
	render_manual_result_node(render_manual_result_node)
	maybe_offer_notify_node(maybe_offer_notify_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_scheme_node;
	load_scheme_node --> resolve_manual_inputs_node;
	resolve_manual_inputs_node --> check_manual_files_node;
	check_manual_files_node -.-> __end__;
	check_manual_files_node -.-> build_manual_run_context_node;
	build_manual_run_context_node --> scheme_execution_graph;
	scheme_execution_graph --> render_manual_result_node;
	render_manual_result_node --> maybe_offer_notify_node;
	maybe_offer_notify_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
