---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	decide_prepare_node(decide_prepare_node)
	execute_proc_node(execute_proc_node)
	build_recon_inputs_node(build_recon_inputs_node)
	execute_recon_node(execute_recon_node)
	build_recon_observation_node(build_recon_observation_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> decide_prepare_node;
	decide_prepare_node -.-> execute_proc_node;
	decide_prepare_node -.-> build_recon_inputs_node;
	execute_proc_node --> build_recon_inputs_node;
	build_recon_inputs_node --> execute_recon_node;
	execute_recon_node --> build_recon_observation_node;
	build_recon_observation_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
