import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Loader2, MonitorSmartphone, RefreshCw } from 'lucide-react';

/**
 * Browser playbook registration panel.
 *
 * Reuses the slot previously occupied by the `browser` reserved card. v1 flow:
 *   1. Operator picks an existing browser_playbook data source (or creates one).
 *   2. Operator pastes the playbook JSON (generated by Claude Code / codex) and the
 *      merchant-issued sub-account credentials.
 *   3. Submitting calls POST /api/data-sources/{source_id}/browser-playbook/register,
 *      which writes draft + verifying + a verification sync_job and returns its id.
 *   4. The panel polls GET /api/sync-jobs/{verification_sync_job_id} every 5s.
 *   5. On `job_status='success'` the panel surfaces a "激活" button that calls
 *      POST /api/data-sources/browser-playbook/finalize to atomically flip both rows.
 *   6. On failure the panel shows `browser_fail_reason` + `error_message` and offers retry.
 *
 * Polling is bounded (max ~20min) so the tab doesn't keep firing forever; the operator
 * can hit "刷新" to re-check after that.
 */

interface BrowserPlaybookPanelProps {
  authToken: string | null;
}

interface DataSourceRow {
  id: string;
  code?: string;
  name?: string;
  source_kind?: string;
  status?: string;
}

interface DatasetRow {
  id: string;
  dataset_code?: string;
  resource_key?: string;
  source_type?: string;
  publish_status?: string;
}

interface SyncJobRow {
  id: string;
  job_status?: string;
  is_verification?: boolean;
  browser_fail_reason?: string;
  error_message?: string;
  request_payload?: Record<string, unknown>;
}

interface RegisterResponse {
  success: boolean;
  status?: string;
  verification_sync_job_id?: string;
  verification_biz_date?: string;
  playbook?: Record<string, unknown> | null;
  binding?: Record<string, unknown> | null;
  message?: string;
}

const POLL_INTERVAL_MS = 5000;
const POLL_MAX_DURATION_MS = 20 * 60 * 1000;

function yesterday(): string {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toISOString().slice(0, 10);
}

export function BrowserPlaybookPanel({ authToken }: BrowserPlaybookPanelProps) {
  const authHeaders = useMemo(
    () => ({
      'Content-Type': 'application/json',
      ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
    }),
    [authToken],
  );

  const [sources, setSources] = useState<DataSourceRow[]>([]);
  const [selectedSourceId, setSelectedSourceId] = useState<string>('');
  const [datasets, setDatasets] = useState<DatasetRow[]>([]);
  const [loadingSources, setLoadingSources] = useState(false);
  const [loadingDatasets, setLoadingDatasets] = useState(false);
  const [error, setError] = useState<string>('');

  const [playbookId, setPlaybookId] = useState('qianniu-daily-bill-export');
  const [version, setVersion] = useState('1.0.0');
  const [title, setTitle] = useState('千牛资金日账单');
  const [playbookBodyText, setPlaybookBodyText] = useState('');
  const [egressGroup, setEgressGroup] = useState('');
  const [credentialUsername, setCredentialUsername] = useState('');
  const [credentialPassword, setCredentialPassword] = useState('');
  const [verificationBizDate, setVerificationBizDate] = useState(yesterday());
  const [datasetId, setDatasetId] = useState('');
  // shop_id is derived server-side from data_source.code; agent_id is picked server-side
  // from the registered agents pool (single-node v1). Operators don't see either.

  const [submitting, setSubmitting] = useState(false);
  const [registerResult, setRegisterResult] = useState<RegisterResponse | null>(null);
  const [verificationJob, setVerificationJob] = useState<SyncJobRow | null>(null);
  const [finalizing, setFinalizing] = useState(false);
  const [finalizeMessage, setFinalizeMessage] = useState<string>('');

  const refreshSources = useCallback(async () => {
    if (!authToken) return;
    setLoadingSources(true);
    setError('');
    try {
      const response = await fetch('/api/data-sources?source_kind=browser_playbook', {
        headers: authHeaders,
      });
      if (!response.ok) throw new Error(`数据源列表请求失败: ${response.status}`);
      const body = await response.json();
      const rows = (body?.sources ?? []) as DataSourceRow[];
      setSources(rows);
      if (rows.length && !selectedSourceId) {
        setSelectedSourceId(rows[0].id);
      }
    } catch (e) {
      setError(String((e as Error)?.message || e));
    } finally {
      setLoadingSources(false);
    }
  }, [authHeaders, authToken, selectedSourceId]);

  const refreshDatasets = useCallback(async () => {
    if (!authToken || !selectedSourceId) {
      setDatasets([]);
      return;
    }
    setLoadingDatasets(true);
    try {
      const response = await fetch(`/api/data-sources/${selectedSourceId}/datasets?only_published=true`, {
        headers: authHeaders,
      });
      if (!response.ok) throw new Error(`数据集列表请求失败: ${response.status}`);
      const body = await response.json();
      const all = (body?.datasets ?? []) as DatasetRow[];
      const filtered = all.filter(
        (d) => String(d.source_type || '') === 'browser_collection_records',
      );
      setDatasets(filtered);
      if (filtered.length && !datasetId) {
        setDatasetId(filtered[0].id);
      }
    } catch (e) {
      setError(String((e as Error)?.message || e));
    } finally {
      setLoadingDatasets(false);
    }
  }, [authHeaders, authToken, selectedSourceId, datasetId]);

  useEffect(() => {
    void refreshSources();
  }, [refreshSources]);

  useEffect(() => {
    void refreshDatasets();
  }, [refreshDatasets]);

  // Poll verification sync_job after a successful register.
  useEffect(() => {
    const jobId = registerResult?.verification_sync_job_id;
    if (!jobId || !authToken) return;
    if (verificationJob?.job_status === 'success' || verificationJob?.job_status === 'failed') return;

    const startedAt = Date.now();
    let cancelled = false;
    const tick = async () => {
      if (cancelled) return;
      try {
        const response = await fetch(`/api/sync-jobs/${jobId}`, { headers: authHeaders });
        if (response.ok) {
          const body = await response.json();
          const job = (body?.job ?? null) as SyncJobRow | null;
          if (job) {
            setVerificationJob(job);
            if (job.job_status === 'success' || job.job_status === 'failed') return;
          }
        }
      } catch {
        // soft-fail; next tick will retry
      }
      if (Date.now() - startedAt < POLL_MAX_DURATION_MS && !cancelled) {
        setTimeout(tick, POLL_INTERVAL_MS);
      }
    };
    setTimeout(tick, POLL_INTERVAL_MS);
    return () => {
      cancelled = true;
    };
  }, [registerResult?.verification_sync_job_id, authToken, authHeaders, verificationJob?.job_status]);

  const handleRegister = useCallback(async () => {
    if (!authToken) {
      setError('未登录');
      return;
    }
    if (!selectedSourceId) {
      setError('请先选择 browser_playbook 数据源');
      return;
    }
    if (!datasetId) {
      setError('请先发布一条 browser_collection_records 数据集再注册 playbook');
      return;
    }
    let parsedBody: unknown;
    try {
      parsedBody = JSON.parse(playbookBodyText || '{}');
    } catch (e) {
      setError(`playbook JSON 解析失败: ${(e as Error).message}`);
      return;
    }
    if (!parsedBody || typeof parsedBody !== 'object') {
      setError('playbook JSON 必须是对象');
      return;
    }
    setSubmitting(true);
    setError('');
    setVerificationJob(null);
    setFinalizeMessage('');
    try {
      const response = await fetch(`/api/data-sources/${selectedSourceId}/browser-playbook/register`, {
        method: 'POST',
        headers: authHeaders,
        body: JSON.stringify({
          playbook_id: playbookId,
          version,
          title,
          playbook_body: parsedBody,
          // shop_id 与 agent_id 由服务端派生:shop_id 取自 data_source.code,
          // agent_id 取自后端默认采集节点配置(v1 单节点)。
          credential_username: credentialUsername,
          credential_password: credentialPassword,
          verification_biz_date: verificationBizDate,
          dataset_id: datasetId,
          egress_group: egressGroup,
        }),
      });
      const body = await response.json();
      if (!response.ok || !body?.success) {
        setError(String(body?.detail || body?.error || '注册失败'));
        return;
      }
      setRegisterResult(body as RegisterResponse);
      // Don't keep password in memory longer than needed.
      setCredentialPassword('');
    } catch (e) {
      setError(String((e as Error)?.message || e));
    } finally {
      setSubmitting(false);
    }
  }, [
    authToken,
    authHeaders,
    selectedSourceId,
    datasetId,
    playbookBodyText,
    playbookId,
    version,
    title,
    credentialUsername,
    credentialPassword,
    verificationBizDate,
    egressGroup,
  ]);

  const handleFinalize = useCallback(async () => {
    const jobId = registerResult?.verification_sync_job_id;
    if (!jobId) return;
    setFinalizing(true);
    setError('');
    setFinalizeMessage('');
    try {
      const response = await fetch('/api/data-sources/browser-playbook/finalize', {
        method: 'POST',
        headers: authHeaders,
        body: JSON.stringify({ verification_sync_job_id: jobId }),
      });
      const body = await response.json();
      if (!response.ok || !body?.success) {
        setError(String(body?.detail || body?.error_message || body?.error || '激活失败'));
        return;
      }
      setFinalizeMessage(String(body?.message || '激活成功'));
    } catch (e) {
      setError(String((e as Error)?.message || e));
    } finally {
      setFinalizing(false);
    }
  }, [registerResult?.verification_sync_job_id, authHeaders]);

  const verificationStatus = verificationJob?.job_status || (registerResult ? 'pending' : '');
  const showFinalize = verificationStatus === 'success' && !finalizeMessage;
  const showFailure = verificationStatus === 'failed';

  return (
    <div className="space-y-5">
      <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-base font-semibold text-text-primary">
              <MonitorSmartphone className="h-4 w-4" />
              浏览器抓取
            </div>
            <p className="mt-1 text-sm text-text-secondary">
              注册商家 playbook + 子账号凭证,Tally 自动触发首次验证 dry-run,通过后激活进入 cron。
            </p>
          </div>
          <button
            type="button"
            onClick={() => {
              void refreshSources();
              void refreshDatasets();
            }}
            className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-surface px-3 py-1.5 text-xs text-text-secondary hover:bg-surface-secondary"
          >
            <RefreshCw className="h-3.5 w-3.5" /> 刷新
          </button>
        </div>

        {error && (
          <div className="mt-3 flex items-start gap-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
            <AlertCircle className="mt-0.5 h-4 w-4 flex-none" />
            <div>{error}</div>
          </div>
        )}
      </div>

      <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm">
        <div className="text-sm font-semibold text-text-primary">1. 选择 browser_playbook 数据源</div>
        <div className="mt-3 flex flex-wrap items-center gap-2">
          {loadingSources && <Loader2 className="h-4 w-4 animate-spin text-text-secondary" />}
          {!loadingSources && sources.length === 0 && (
            <div className="text-sm text-text-secondary">
              暂无 browser_playbook 数据源。请先在数据连接中创建一个 source_kind=browser_playbook 的数据源(可用 MCP 工具 data_source_create)。
            </div>
          )}
          {sources.map((source) => (
            <button
              key={source.id}
              type="button"
              onClick={() => setSelectedSourceId(source.id)}
              className={`rounded-lg border px-3 py-1.5 text-xs ${
                selectedSourceId === source.id
                  ? 'border-cyan-500 bg-cyan-50 text-cyan-700'
                  : 'border-border bg-surface text-text-secondary hover:bg-surface-secondary'
              }`}
            >
              {source.name || source.code || source.id}
            </button>
          ))}
        </div>
        {selectedSourceId && (
          <div className="mt-4">
            <div className="text-xs text-text-secondary">已发布的 browser_collection_records 数据集:</div>
            {loadingDatasets ? (
              <Loader2 className="mt-2 h-4 w-4 animate-spin text-text-secondary" />
            ) : datasets.length === 0 ? (
              <div className="mt-2 text-xs text-amber-700">
                该数据源下没有已发布的 browser_collection_records 数据集。注册会被后端拒绝;请先在数据集管理中发布一条。
              </div>
            ) : (
              <select
                value={datasetId}
                onChange={(e) => setDatasetId(e.target.value)}
                className="mt-2 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm"
              >
                {datasets.map((d) => (
                  <option key={d.id} value={d.id}>
                    {d.dataset_code || d.resource_key || d.id}
                  </option>
                ))}
              </select>
            )}
          </div>
        )}
      </div>

      <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm">
        <div className="text-sm font-semibold text-text-primary">2. 填写 playbook + 商家子账号凭证</div>
        <div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-2">
          <Field label="playbook_id" value={playbookId} onChange={setPlaybookId} />
          <Field label="version" value={version} onChange={setVersion} />
          <Field label="title" value={title} onChange={setTitle} />
          <Field label="egress_group(可选)" value={egressGroup} onChange={setEgressGroup} />
          <Field
            label="子账号 username(商家分配)"
            value={credentialUsername}
            onChange={setCredentialUsername}
          />
          <Field
            label="子账号 password"
            value={credentialPassword}
            onChange={setCredentialPassword}
            type="password"
          />
          <Field
            label="verification biz_date"
            value={verificationBizDate}
            onChange={setVerificationBizDate}
            type="date"
          />
        </div>
        <div className="mt-3">
          <div className="text-xs text-text-secondary">playbook_body JSON(粘贴 Claude Code / codex 生成的对象)</div>
          <textarea
            value={playbookBodyText}
            onChange={(e) => setPlaybookBodyText(e.target.value)}
            className="mt-1 h-48 w-full rounded-lg border border-border bg-surface p-3 font-mono text-xs"
            placeholder='{"schema_version": "1.0", "playbook_id": "...", "steps": [...], "output": {...}, "quality_gate": {...}}'
          />
        </div>
        <div className="mt-4 flex items-center justify-end gap-2">
          <button
            type="button"
            disabled={submitting || !selectedSourceId || !datasetId}
            onClick={() => void handleRegister()}
            className="inline-flex items-center gap-2 rounded-lg bg-cyan-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
          >
            {submitting && <Loader2 className="h-4 w-4 animate-spin" />}
            注册并触发首次验证
          </button>
        </div>
      </div>

      {registerResult && (
        <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm">
          <div className="text-sm font-semibold text-text-primary">3. 验证 dry-run 状态</div>
          <div className="mt-2 text-xs text-text-secondary">
            sync_job_id: <span className="font-mono">{registerResult.verification_sync_job_id}</span>
          </div>
          <div className="mt-2 text-xs text-text-secondary">
            biz_date: {registerResult.verification_biz_date}
          </div>
          <div className="mt-3">
            {verificationStatus === '' || verificationStatus === 'pending' || verificationStatus === 'running' ? (
              <div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-700">
                <Loader2 className="h-3 w-3 animate-spin" />
                {verificationStatus === 'running' ? '采集中…' : '等待 browser-agent 领取…'}
              </div>
            ) : verificationStatus === 'success' ? (
              <div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-700">
                <CheckCircle2 className="h-3 w-3" /> 验证通过
              </div>
            ) : (
              <div className="inline-flex items-center gap-2 rounded-full bg-red-50 px-3 py-1 text-xs text-red-700">
                <AlertCircle className="h-3 w-3" /> 验证失败
              </div>
            )}
          </div>
          {showFailure && verificationJob && (
            <div className="mt-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
              <div className="font-semibold">{verificationJob.browser_fail_reason || 'FAILED'}</div>
              <div className="mt-1 whitespace-pre-wrap text-xs">{verificationJob.error_message || ''}</div>
              <div className="mt-2 text-xs">
                修复 playbook 或凭证后,在上方表单重新注册即可——本次失败的 sync_job 不会被生产 claim,等于沉淀为审计记录。
              </div>
            </div>
          )}
          {showFinalize && (
            <div className="mt-3 flex items-center justify-end">
              <button
                type="button"
                disabled={finalizing}
                onClick={() => void handleFinalize()}
                className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
              >
                {finalizing && <Loader2 className="h-4 w-4 animate-spin" />}
                激活 playbook + binding
              </button>
            </div>
          )}
          {finalizeMessage && (
            <div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700">
              {finalizeMessage}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function Field({
  label,
  value,
  onChange,
  type = 'text',
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  type?: string;
}) {
  return (
    <label className="block text-xs text-text-secondary">
      {label}
      <input
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text-primary"
      />
    </label>
  );
}
