"""Design-session executor abstraction.

This module keeps a thin adapter interface so we can switch to deepagent later.
Current environment does not provide deepagent package, so we use fallback logic.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol

from models import SchemeDesignSession


@dataclass(slots=True)
class SchemeDesignExecutorResult:
    assistant_message: str
    loaded_skills: list[str] = field(default_factory=list)
    open_questions: list[str] = field(default_factory=list)
    proc_draft_json: dict[str, Any] | None = None
    recon_draft_json: dict[str, Any] | None = None
    proc_trial_result: dict[str, Any] | None = None
    recon_trial_result: dict[str, Any] | None = None
    pending_interrupt: dict[str, Any] | None = None


class SchemeDesignExecutor(Protocol):
    """Adapter interface for design session turns."""

    name: str

    async def run_turn(
        self,
        *,
        session: SchemeDesignSession,
        user_message: str,
        is_resume: bool = False,
    ) -> SchemeDesignExecutorResult: ...


class FallbackSchemeDesignExecutor:
    """No-dependency fallback executor.

    Behavior:
    - mimics skill-oriented workflow and keeps session moving
    - emits placeholder proc/recon drafts when users ask to continue/configure
    - leaves actual deepagent integration to a future adapter
    """

    name = "fallback-no-deepagent"

    async def run_turn(
        self,
        *,
        session: SchemeDesignSession,
        user_message: str,
        is_resume: bool = False,
    ) -> SchemeDesignExecutorResult:
        text = (user_message or "").strip()
        normalized = text.lower()

        should_build_proc = (
            not session.drafts.proc_draft_json
            and (
                not text
                or "proc" in normalized
                or "整理" in text
                or "准备" in text
                or "continue" in normalized
                or "next" in normalized
            )
        )
        should_build_recon = (
            not session.drafts.recon_draft_json
            and (
                not text
                or "recon" in normalized
                or "对账" in text
                or "核对" in text
                or "continue" in normalized
                or "next" in normalized
            )
        )

        proc_draft = self._build_proc_draft(session) if should_build_proc else None
        recon_draft = self._build_recon_draft(session) if should_build_recon else None
        open_questions = self._build_open_questions(session)

        phase = "恢复会话" if is_resume else "处理消息"
        assistant_message = (
            f"[{phase}] 当前运行在 fallback 设计执行器（尚未接入 deepagent 运行时）。"
            " 已按 proc-config / recon-config 的最小路径维护草稿。"
            " 你可以继续补充业务目标、样本结构、匹配字段与容差，我会持续更新草稿。"
        )

        return SchemeDesignExecutorResult(
            assistant_message=assistant_message,
            loaded_skills=["proc-config", "recon-config"],
            open_questions=open_questions,
            proc_draft_json=proc_draft,
            recon_draft_json=recon_draft,
            pending_interrupt={
                "type": "design_review",
                "message": "请确认当前草稿方向，或继续补充约束。",
            },
        )

    def _build_open_questions(self, session: SchemeDesignSession) -> list[str]:
        questions: list[str] = []
        if not session.biz_goal.strip():
            questions.append("请补充业务目标（例如：平台结算对账、回款核对）。")
        if not session.source_description.strip():
            questions.append("请补充左右数据来源说明（文件/数据集来源及用途）。")
        if not session.sample_files and not session.sample_datasets:
            questions.append("请至少提供一个样本文件或样本数据集。")
        if not session.drafts.proc_draft_json:
            questions.append("是否需要先做数据准备（proc）？若需要请说明目标表。")
        if not session.drafts.recon_draft_json:
            questions.append("请确认对账主键、金额字段和容差。")
        return questions

    def _build_proc_draft(self, session: SchemeDesignSession) -> dict[str, Any]:
        target = "recon_ready_dataset"
        if session.scheme_name.strip():
            normalized = session.scheme_name.strip().replace(" ", "_").lower()
            target = f"{normalized}_recon_ready"
        return {
            "version": "draft-1",
            "role_desc": "fallback proc draft",
            "steps": [],
            "target_table": target,
            "notes": "placeholder draft generated by fallback executor",
        }

    def _build_recon_draft(self, session: SchemeDesignSession) -> dict[str, Any]:
        source_table = "left_recon_ready"
        target_table = "right_recon_ready"
        if session.drafts.proc_draft_json:
            table = str(session.drafts.proc_draft_json.get("target_table") or "").strip()
            if table:
                source_table = table
        return {
            "schema_version": "draft-1",
            "rule_name": session.scheme_name or "draft_recon_rule",
            "rules": [
                {
                    "enabled": True,
                    "source_file": {
                        "table_name": source_table,
                        "identification": {
                            "match_by": "table_name",
                            "match_value": source_table,
                            "match_strategy": "exact",
                        },
                    },
                    "target_file": {
                        "table_name": target_table,
                        "identification": {
                            "match_by": "table_name",
                            "match_value": target_table,
                            "match_strategy": "exact",
                        },
                    },
                    "recon": {
                        "key_columns": {"mappings": []},
                        "compare_columns": {"columns": []},
                    },
                }
            ],
            "notes": "placeholder draft generated by fallback executor",
        }

